GET http://localhost:3000/movies

###

GET http://localhost:3000/people

###

GET http://localhost:3000/favorites

###

POST http://localhost:3000/favorites
content-type: application/json
{
    "name": "Return of the Jedi",
    "type": "movie"
    "url": "https://swapi.dev/api/films/3/"
}