version: "3.8"

services:
  mongodb:
    image: "mongo"
    env_file:
      - ./env/mongodb.env
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./env/backend.env
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - /app/node_modules
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

volumes:
  data:
  logs:
